######################################################################
# Automatically generated by qmake (2.01a) Sat May 16 13:09:29 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += script

# Input
SOURCES += hp15c.cpp
